apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deployment
  labels:
    app: healthapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthapp
  template:
    metadata:
      labels:
        app: healthapp
    spec:
      containers:
        - name: healthapp-container
          image: sravani629/healthapp-deployment:14
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-service
spec:
  type: NodePort
  selector:
    app: healthapp
  ports:
    - port: 8081
      targetPort: 8081
